name: Android Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Find APK
        run: find app/build/outputs -type f
